### ISSUE TITLE
Strange single time error in firefox

### ISSUE THREAD

**Issue by vklachkov** [anticensority/runet-censorship-bypass#103] opened 2022-01-05 18:36 UTC
```
{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0",
  "platform": "Win32",
  "version": "0.0.1.56",
  "ext-error": {
    "message": "TypeError: can't access dead object",
    "filename": "moz-extension://5b621cac-0388-4b35-8987-327e30ab104d/37-sync-pac-script-with-pac-provider-api.js",
    "lineno": 57,
    "colno": 9,
    "error": {
      "fileName": "moz-extension://5b621cac-0388-4b35-8987-327e30ab104d/37-sync-pac-script-with-pac-provider-api.js",
      "lineNumber": 57,
      "columnNumber": 9,
      "message": "can't access dead object",
      "name": "TypeError"
    },
    "type": "error"
  }
}
```

**Comment by ilyaigpetrov** [comment] 2022-01-06 07:56
Closing as a dupe of https://github.com/anticensority/runet-censorship-bypass/issues/91.

**Closed as completed by ilyaigpetrov** 2022-01-06 07:56 UTC
